### ISSUE TITLE
Hey, looking for a complete example.

### ISSUE THREAD

**Issue by mangelajo** [jedrzejboczar/usbd-dfu-rt#1]
Hey, I was trying to use your class together with https://github.com/vitalyvb/usbd-dfu-example. To make a complete example of bootloader + app&runtime class.

Do you have any example I could look at?

**Comment by mangelajo** [comment]
And, of course, I forgot to thank you for sharing this, really appreciated!

**Comment by jedrzejboczar** [comment]
Hi, I've just added an example in https://github.com/jedrzejboczar/usbd-dfu-rt/commit/6139d2f6f0894cf2a31ec275fb38e72748c8f831. This is specifically for STM32F072 as this one is convenient enough to have a builtin DFU-capable bootloader. I've tested it on some hardware and everything seems to work fine, but I haven't tested it extensively so I wouldn't be surprised if there were some minor bugs. Hopefully the example is readable, but if something is missing feel free to ask.

**Comment by mangelajo** [comment]
Thanks a lot.

I am trying to prepare some examples of your runtime and the other dfu bootloader to be shared in the https://fwupd.org project, so peripheral vendors working with rust would have out of the box examples to work with fwupd.

I have your runtime already working mostly with fwupd. 

I needed to circumvent part of fwupd because your runtime does not implement GETSTATUS, but I will try to send you a PR with the GETSTATUS support.

**Comment by mangelajo** [comment]
👏 for the example!! :)

**Comment by mangelajo** [comment]
Fixed in https://github.com/jedrzejboczar/usbd-dfu-rt/commit/6139d2f6f0894cf2a31ec275fb38e72748c8f831
